.TH OPENVPN3-INDICATOR "1" "January 2024" "version 0.1"
.SH NAME
openvpn3\-indicator \- Simple indicator application for OpenVPN3
.SH SYNOPSIS
.B openvpn3\-indicator
[\-\^\-help|\-\^\-version|\-\^\-silent|\-\^\-verbose|\-\^\-debug|\-\^\-clear\-secret\-storage|\-\^\-repair]
.SH DESCRIPTION
This is a simple indicator application that controls OpenVPN3 tunnels.
It is based on D-Bus interface provided by OpenVPN3 Linux client.
It is a temporary solution until Network Manager supports OpenVPN3.
.SH OPTIONS
.TP
.BR \-h ", " \-\^\-help
Show help and exit
.TP
.BR \-V ", " \-\^\-version
Show program's version number and exit
.TP
.BR \-s ", " \-\^\-silent
Show less information
.TP
.BR \-v ", " \-\^\-verbose
Show more information
.TP
.BR \-d ", " \-\^\-debug
Show debug information
.TP
.BR \-c ", " \-\^\-clear\-secret\-storage
Remove all credentials stored in the secret storage
.TP
.BR \-r ", " \-\^\-repair
Ask the already running instance to re-create its tray icons and exit.
Starting the application a second time without options has the same effect.
Use this when the tray icon has disappeared while the application is still running.
.SH SETTINGS
Settings are stored with GSettings under the schema
.BR net.openvpn.openvpn3_indicator
and can be changed from the indicator menu or with
.BR gsettings (1).
.TP
.B indicator-mode
.RB \(oq single \(cq
shows one tray icon that represents all connections (default);
.RB \(oq per\-session \(cq
shows one tray icon for every running connection.
.TP
.B startup-action
Connection to start when the indicator starts: empty for none,
.RB \(oq RESTART \(cq
for the most recently started configuration, or
.RB \(oq STARTNAME:<name> \(cq
for a configuration by name.
.SH AUTHORS
Grzegorz Gutowski <grzegorz.gutowski@uj.edu.pl>
