#!/usr/bin/env python3

import argparse
import os
import pathlib
import subprocess

os.environ['TZ'] = 'UTC'
os.environ['LC_ALL'] = 'en_US.UTF-8'

try:
    parser = argparse.ArgumentParser('semver script for openvpn3-indicator')
    parser.add_argument('--scriptdir', default=pathlib.Path(__file__).parent)
    parser.add_argument('--devel', action='store_true')
    args = parser.parse_args()
    scriptdir=pathlib.Path(args.scriptdir)
    gitdir=scriptdir.parent

    subprocess.run(['git', 'config', '--global', '--add', 'safe.directory', str(gitdir)])

    describe_run = subprocess.run(['git', '-C', str(gitdir), 'describe', '--tags'], capture_output=True)
    describe = str(describe_run.stdout, 'utf-8').strip()
    tag = describe.split('-')[0]
    ver = '.'.join((tag.lstrip('v').split('.')+['0']*3)[:3])

    revparse_run = subprocess.run(['git', 'rev-parse', '--short', tag], capture_output=True)
    revparse = str(revparse_run.stdout, 'utf-8').strip()

    timestamp_hash_run = subprocess.run(['git', '-C', str(gitdir), 'log', '-n', '1', '--format=format:%cd_%h', '--date=format-local:%Y%m%d%H%M%S'], capture_output=True)
    timestamp_hash = str(timestamp_hash_run.stdout, 'utf-8').strip()
    timestamp, hash = timestamp_hash.split('_')

    devel = args.devel or (revparse != hash)

    if devel:
        print(f'{ver}-{timestamp}.devel')
    else:
        print(f'{ver}')
except:
    print('0.0.0-19700101000000.undefined')
