on:
  push:
    branches:
    - main
jobs:
  launchpad:
    name: Deploy to Launchpad
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-tags: true
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get -f -y install make devscripts dput dpkg-dev debhelper desktop-file-utils build-essential
    - name: Install GPG Key
      env:
        KEY: ${{ secrets.GPG_LAUNCHPAD_KEY }}
      run: |
        echo "${KEY}" | gpg --import
    - name: Install SSH Key
      env:
        KEY: ${{ secrets.SSH_LAUNCHPAD_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${KEY}" > ~/.ssh/id_ed25519
        echo "Host ppa.launchpad.net" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
        echo "  GlobalKnownHostsFile /dev/null" >> ~/.ssh/config
    - name: Deploy
      run: |
        make -C .launchpad
